### ISSUE TITLE
关于项目

### ISSUE THREAD

**Issue by YangFong** [Summer-andy/react-loading-typescript#2]
您好，我是一个今天刚关注的使用者，发现一些问题，来询问一下。

关于 TypeScript，在 npm 上默认安装的版本是 `1.7.2`，该版本并没有支持 TS，在使用 TS 开发时会导致一定的不便之处。我通过 npm 发现了 `1.8.0-alpha.2`，但它当前还未完善，直观的表现在于 `color`、`size` 等字段是必填的（即默认值概念不存在）。

后续是否有将其完善的计划在内呢？或者我个人尝试着完善它

**Comment by Summer-andy** [comment]
你可以提pr哦
